#!/system/bin/sh

. /system/etc/chroot.cfg

unset LD_PRELOAD
export PATH="/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:$PATH"
export HOME="/root"
export SHELL="/bin/bash"
export TERM="xterm"

echo "########chrootset at `date`########" | tee -a $LOGFILE

# For using fuse (ex.sshfs)
chmod 777 /dev/fuse

for dir in "/proc" "/sys" "/dev" "/dev/pts"
do
    if [ ! -e ${CHROOT_DIR}/${dir} ]
    then
	mkdir ${CHROOT_DIR}/${dir}
    fi
    echo "mount ${dir} ${CHROOT_DIR}/${dir}" | tee -a $LOGFILE
    mount -o bind ${dir} ${CHROOT_DIR}/${dir}
done

for dir in $EXTRA_DIRS
do
    DIRNAME=`echo ${dir} | sed 's/[[:print:]]*\///g'`
    if [ ! -e ${CHROOT_DIR}/mnt/${DIRNAME} ]
    then
	mkdir ${CHROOT_DIR}/mnt/${DIRNAME}
    fi
    echo "mount ${dir} to ${CHROOT_DIR}/mnt/${DIRNAME}" | tee -a $LOGFILE
    mount -o bind $dir ${CHROOT_DIR}/mnt/${DIRNAME}
done

mount -o remount,exec,dev,suid /data

# Start services (ex.sshd)

echo "Init daemon is ${INIT}." | tee -a $LOGFILE

if [ $INIT -e "upstart" ]
then
    for service in $SERVICES
    do
	chroot $CHROOT_DIR service $service start 
	echo "${service} service started." | tee -a $LOGFILE
    done
elif [ $INIT -e "systemd" ]
then
    for service in $SERVICES
    do
	chroot $CHROOT_DIR systemctl start $service
	echo "${service} service started." | tee -a $LOGFILE
    done     
fi
echo "chrootset finished." | tee -a $LOGFILE

chmod 644 $LOGFILE
