#!/system/bin/sh

. /system/etc/chroot.cfg

# For using fuse (ex.sshfs)
chmod 777 /dev/fuse

for dir in "proc" "sys" "dev" "dev/pts"
do
    if [ ! -e ${CHROOT_DIR}/${dir} ]
    then
	mkdir ${CHROOT_DIR}/${dir}
    fi

    mount -o bind ${dir} ${CHROOT_DIR}/${dir}
done

for dir in $EXTRA_DIRS
do
    $DIRNAME=`echo $dir | sed 's/[[:print:]]*\///g'`
    mount -o bind $dir $DIRNAME
done

mount -o remount,exec,dev,suid /data
